  // this file is not to be explicitly included in project.
    //#include "pch_core.h"
    #include <QWidget>
    #include <QMainWindow>
    #include <QStyle>
    #include <QFont>
    #include <QIcon>
    #include <QEvent>
    #include <QBrush>
    #include <QScrollArea>
    #include <QModelIndex>
    #include <QPalette>
    #include <QSize>
    #include <QHBoxLayout>
    #include <QVBoxLayout>
    #include <QAbstractItemView>
    #include <QRect>
    #include <QAction>
    #include <QScrollArea>
    #include <QAbstractItemModel>
    #include <QGridLayout>
    #include <QColor>

    
      // this file is not to be explicitly included in project.
    #include <QTimer>
    #include <QWaitCondition>
    #include <qobject.h>
    #include <QTime>
    #include <QMutex>
    #include <QStack>
    #include <QTextCodec>
    #include <QDateTime>
    #include <QQueue>
    #include <QEventLoop>
    #include <QVariantHash>
    #include <QSqlField>
    #include <QDataStream>
    #include <QVectorIterator>
    #include <QFileInfo>
    #include <QtGlobal>
    #include <qcryptographichash.h>
    #include <QTextStream>
    #include <QReadWriteLock>
    #include <QReadLocker>
    #include <QWriteLocker>
    #include <QSemaphore>
    #include <QProcess>
    #include <QIODevice>
    #include <QCryptographicHash>
    #include <QVariant>
    #include <QVariantMap>
    #include <QMap>
    #include <QVector>
    #include <QStringList>
    #include <QDir>
    #include <QJsonObject>
    #include <QJsonArray>
    #include <QJsonDocument>
    #include <QPointer>
    #include <QList>
    #include <QFile>
    #include <QObject>
    #include <QHash>
    #include <QMutexLocker>
    #include <QVector>
    #include <QStringList>
    #include <QDir>
    #include <QPair>
    #include <QMetaEnum>
    #include <QSharedPointer>
    #include <QScopedPointer>
    #include <QWeakPointer>
    #include <QDebug>
    #include <QString>
    #include <QSettings>
    #include <QThread>
    #include <QFuture>
    #include <QFutureWatcher>
    #include <QSqlRecord>
    #include <QtConcurrent>
    #include <QThreadStorage>
    #include <QUuid>
    #include <QRegExp>
    #include <QMetaType>
    #include <QtCore/qglobal.h>

    #include <memory>
    #include <initializer_list>
    #include <functional>
    #include <algorithm>
    #include <stdexcept>
    #include <typeinfo>
    #include <mutex>
    #include <tuple>

    #include <sstream>
    #include <chrono>
    #include <thread>
    #include <typeinfo>
    #include <stdexcept>
    #include <limits>
    #include <cmath>

#include "logger/QsLog.h"
#include "logger/QsLogDest.h"

